import React from 'react';
import { FileText, Scale, Zap, AlertTriangle, Copyright, Ban } from 'lucide-react';
import './LegalPages.css';

const TermsConditions: React.FC = () => {
  return (
    <div className="legal-container">
      <header className="legal-hero">
        <div className="contact-icon pulse-eco">
          <FileText size={32} />
        </div>
        <h1>Terms & Conditions</h1>
        <p>The framework for our partnership. Understanding the rules of the CHLOSE Ecosystem.</p>
      </header>

      <div className="glass-card legal-card">
        <section className="legal-section">
          <h2><Scale size={24} /> Acceptable Use</h2>
          <p>
            By accessing the <strong>CHLOSE Console</strong>, <strong>PlastiNet</strong>, or <strong>Chloe AI</strong>, 
            you agree to use these platforms for their intended purpose: promoting environmental sustainability and 
            responsible resource management.
          </p>
          <div className="highlight-box">
            <p><strong>Warning:</strong> Abuse, fraudulent activity, or attempts to circumvent platform security may lead to immediate account restrictions or permanent suspension.</p>
          </div>
        </section>

        <section className="legal-section">
          <h2><Zap size={24} /> PLC Reward System</h2>
          <p>
            The <strong>PLC (PlastiNet Ledger Credit)</strong> is a platform-specific reward system designed to incentivize 
            environmental action.
          </p>
          <ul>
            <li><strong>Not Cryptocurrency:</strong> PLC is a digital reward token and does not constitute cryptocurrency, legal tender, or a financial investment.</li>
            <li><strong>Non-Transferable:</strong> PLC balances are tied to your ecosystem account and cannot be transferred to external wallets or third-party platforms.</li>
            <li><strong>Usage:</strong> PLC can be used within the ecosystem for specific upgrades, features, and partner redemptions as available.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2><Copyright size={24} /> Intellectual Property</h2>
          <p>
            All content, including but not limited to the <strong>LYT-G1 Architecture</strong>, design patterns, and AI logic, 
            are the exclusive property of CHLOSE. 
          </p>
          <p>
            <strong>AI-Generated Insights:</strong> While you own the data you input into Chloe AI, the insights and 
            optimization workflows generated by our models are provided under a limited license for personal or authorized 
            business use.
          </p>
        </section>

        <section className="legal-section">
          <h2><AlertTriangle size={24} /> Disclaimers</h2>
          <ul>
            <li><strong>Platform Availability:</strong> We strive for 99.9% uptime, but do not guarantee uninterrupted access to ecosystem services.</li>
            <li><strong>AI Accuracy:</strong> Environmental mentorship provided by Chloe AI is based on analytical models and should be verified for specific local regulations or safety protocols.</li>
            <li><strong>Future Changes:</strong> We reserve the right to modify platform features, reward structures, and subscription tiers to better serve the ecosystem's mission.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2><Ban size={24} /> Account Responsibilities</h2>
          <p>
            You are responsible for maintaining the security of your authentication sessions. We recommend using 
            authorized devices and enabling all available security features within the CHLOSE Console.
          </p>
        </section>

        <div className="support-info">
          <p>Need clarification on these terms?</p>
          <a href="/contact" className="contact-link">Contact Legal Support</a>
          <p style={{ marginTop: '10px', fontSize: '0.8rem' }}>Powered by CHLOSE Ecosystem Infrastructure</p>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
